In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv('/content/book1.csv')
print(data)

x=np.array(data[['x1','x2']])
y=np.array(data[['y']])
print(x)
print(y)

x_mean=np.mean(x,axis=0)
x_std=np.std(x,axis=0)

print(x_mean)
print(x_std)

x=(x-x_mean)/x_std
print(x)

x_b=np.c_[np.ones((len(x),1)),x]
print(x_b)

theta=np.zeros((x_b.shape[1],1))
print(theta)

alpha=0.01
iterations=1000

for i in range(iterations):
  y_pred=x_b.dot(theta)
  error=y_pred-y

  gradient=(2/len(y))*x_b.T.dot(error)
  theta=theta-(alpha*gradient)

print("optimized weights:",theta)

print("Optimized coefficients (theta):", theta[1:])
print("Optimized intercept:", theta[0])

data_test=pd.read_csv('/content/book1.csv')
print(data_test)
x_test=np.array(data_test[['x1','x2']])
print(x_test)

x_test=(x_test-np.mean(x_test,axis=0))/np.std(x_test,axis=0)
print(x_test)

x_test_b=np.c_[np.ones((len(x_test),1)),x_test]
print(x_test_b)

y_predicted=x_test_b.dot(theta)
print("Predicted value for new input:", y_predicted)

   x1  x2    y
0   1  60  365
1   2  30  105
2   3  40  215
3   4  30  275
4   5  20  390
5   6  45  300
6   7  96  270
[[ 1 60]
 [ 2 30]
 [ 3 40]
 [ 4 30]
 [ 5 20]
 [ 6 45]
 [ 7 96]]
[[365]
 [105]
 [215]
 [275]
 [390]
 [300]
 [270]]
[ 4.         45.85714286]
[ 2.        23.6669062]
[[-1.5         0.59757946]
 [-1.         -0.67001334]
 [-0.5        -0.2474824 ]
 [ 0.         -0.67001334]
 [ 0.5        -1.09254427]
 [ 1.         -0.03621694]
 [ 1.5         2.11869083]]
[[ 1.         -1.5         0.59757946]
 [ 1.         -1.         -0.67001334]
 [ 1.         -0.5        -0.2474824 ]
 [ 1.          0.         -0.67001334]
 [ 1.          0.5        -1.09254427]
 [ 1.          1.         -0.03621694]
 [ 1.          1.5         2.11869083]]
[[0.]
 [0.]
 [0.]]
optimized weights: [[274.28571382]
 [ 20.26023583]
 [ -0.73077068]]
Optimized coefficients (theta): [[20.26023583]
 [-0.73077068]]
Optimized intercept: [274.28571382]
   x1  x2    y
0   1  60  365
1   2  30  105
2   3  40  215
3   4 